// Real-core integration using only programs generated by make_handheld_diagnostics.py.
#include "emulator.h"
#include "log.h"
#include "rom.h"
#include <libretro.h>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <set>
#include <stdexcept>
#include <unistd.h>

extern "C" {
void* sameboy_retro_get_memory_data(unsigned);
size_t sameboy_retro_get_memory_size(unsigned);
void* mgba_retro_get_memory_data(unsigned);
size_t mgba_retro_get_memory_size(unsigned);
}

namespace fs = std::filesystem;
using namespace r2n64;
namespace {
void require(bool condition, const std::string& message) {
    if (!condition) throw std::runtime_error(message);
}
std::vector<unsigned char> readBytes(const fs::path& path) {
    std::ifstream file(path, std::ios::binary);
    require(bool(file), "Cannot read " + path.string());
    return {(std::istreambuf_iterator<char>(file)), {}};
}
void writeBytes(const fs::path& path, const std::vector<unsigned char>& bytes) {
    std::ofstream file(path, std::ios::binary | std::ios::trunc);
    file.write(reinterpret_cast<const char*>(bytes.data()), bytes.size());
    require(bool(file), "Cannot write " + path.string());
}
struct Memory { unsigned char* data; size_t size; };
Memory saveRam(SystemType system) {
    const bool gba = system == SystemType::GameBoyAdvance;
    Memory result{static_cast<unsigned char*>(gba ? mgba_retro_get_memory_data(RETRO_MEMORY_SAVE_RAM) :
                                                  sameboy_retro_get_memory_data(RETRO_MEMORY_SAVE_RAM)),
                  gba ? mgba_retro_get_memory_size(RETRO_MEMORY_SAVE_RAM) : sameboy_retro_get_memory_size(RETRO_MEMORY_SAVE_RAM)};
    require(result.data && result.size > 256, "Missing cartridge SRAM");
    return result;
}
std::array<unsigned char, 8> cartridgeStatus(SystemType system) {
    const auto memory = saveRam(system);
    std::array<unsigned char, 8> bytes{};
    std::copy_n(memory.data, bytes.size(), bytes.begin());
    return bytes;
}
uint64_t pixelHash(const CoreFrame& frame) {
    uint64_t hash = UINT64_C(14695981039346656037);
    for (const auto pixel : frame.pixels) {
        hash ^= pixel & 0xffffff;
        hash *= UINT64_C(1099511628211);
    }
    return hash;
}
std::set<uint32_t> frameColors(const CoreFrame& frame) {
    std::set<uint32_t> colors;
    for (const auto pixel : frame.pixels) colors.insert(pixel & 0xffffff);
    return colors;
}
void verifyPattern(const CoreFrame& frame, SystemType system) {
    const bool gba = system == SystemType::GameBoyAdvance;
    require(frame.width == (gba ? 240u : 160u) && frame.height == (gba ? 160u : 144u) &&
            frame.pixels.size() == size_t(frame.width) * frame.height, "Wrong portable frame geometry");
    std::set<uint32_t> colors;
    unsigned red = 0, green = 0, blue = 0;
    for (const auto pixel : frame.pixels) {
        colors.insert(pixel & 0xffffff);
        const unsigned r = (pixel >> 16) & 255, g = (pixel >> 8) & 255, b = pixel & 255;
        red += r > 120 && r > g * 3 / 2 && r > b * 3 / 2;
        green += g > 120 && g > r * 3 / 2 && g > b * 3 / 2;
        blue += b > 120 && b > r * 3 / 2 && b > g * 3 / 2;
    }
    require(colors.size() >= 4, "Original four-color pattern missing");
    if (system != SystemType::GameBoy)
        require(red > 1000 && green > 1000 && blue > 1000, "Portable RGB pattern missing");
}
void snapshot(const fs::path& path, const CoreFrame& frame) {
    std::ofstream file(path, std::ios::binary);
    file << "P6\n" << frame.width << ' ' << frame.height << "\n255\n";
    for (const auto pixel : frame.pixels) {
        const char rgb[]{char(pixel >> 16), char(pixel >> 8), char(pixel)};
        file.write(rgb, 3);
    }
    require(bool(file), "Cannot write diagnostic preview");
}
void wave(const fs::path& path, const std::vector<int16_t>& samples, unsigned rate) {
    std::ofstream file(path, std::ios::binary);
    const auto u16 = [&](unsigned n) { file.put(char(n)); file.put(char(n >> 8)); };
    const auto u32 = [&](uint32_t n) { u16(n); u16(n >> 16); };
    file.write("RIFF", 4); u32(36 + uint32_t(samples.size() * 2)); file.write("WAVEfmt ", 8);
    u32(16); u16(1); u16(2); u32(rate); u32(rate * 4); u16(4); u16(16);
    file.write("data", 4); u32(uint32_t(samples.size() * 2));
    for (auto sample : samples) u16(static_cast<uint16_t>(sample));
    require(bool(file), "Cannot write diagnostic PCM");
}
void runFrames(Emulator& emulator, const GamepadInput& pad, unsigned count, std::string& error) {
    for (unsigned i = 0; i < count; ++i) require(emulator.run(pad, error), "Run: " + error);
}
void verifyBoot(Emulator& emulator, SystemType system, const GamepadInput& neutral, std::string& error,
                const fs::path& output, bool artifacts) {
    // The bundled free bootstrap animates before running the cartridge.
    // Collect only the final 60 frames so its startup chime cannot pass the PSG test.
    std::vector<int16_t> pcm;
    for (unsigned frame = 0; frame < 360; ++frame) {
        require(emulator.run(neutral, error), "Boot/run: " + error);
        require(emulator.audio().size() % 2 == 0, "Core returned non-stereo audio");
        if (frame >= 300) pcm.insert(pcm.end(), emulator.audio().begin(), emulator.audio().end());
    }
    const auto state = cartridgeStatus(system);
    const char* expected = system == SystemType::GameBoy ? "R2GB" : system == SystemType::GameBoyColor ? "R2GC" : "R2GA";
    require(std::memcmp(state.data(), expected, 4) == 0, "Cartridge CPU program did not boot");
    require(state[6] == 0 && state[7] == 0, "Neutral controller retained input");
    verifyPattern(emulator.frame(), system);
    require(pcm.size() > 10000, "Missing sustained stereo PCM");
    const auto audible = std::count_if(pcm.begin(), pcm.end(), [](int16_t sample) { return std::abs(int(sample)) > 100; });
    require(audible > 5000, "Cartridge PSG tone did not reach the frontend after bootstrap");
    require(emulator.sampleRate() >= 22000 && emulator.sampleRate() <= 96000, "Invalid output sample rate");
    require(emulator.fps() > 59 && emulator.fps() < 61, "Invalid handheld frame rate");
    if (system != SystemType::GameBoyAdvance) require(std::abs(emulator.sampleRate() - 48000) < 1, "SameBoy output rate contract changed");
    const double seconds = (pcm.size() / 2) / emulator.sampleRate();
    const double expectedTone = system == SystemType::GameBoyAdvance ? 128.0 : 512.0;
    for (size_t channel = 0; channel < 2; ++channel) {
        unsigned crossings = 0;
        int previous = pcm[channel], minimum = previous, maximum = previous;
        for (size_t i = channel + 2; i < pcm.size(); i += 2) {
            const int value = pcm[i];
            crossings += (previous < 0 && value > 0) || (previous > 0 && value < 0);
            minimum = std::min(minimum, value); maximum = std::max(maximum, value);
            previous = value;
        }
        const double frequency = crossings / (2 * seconds);
        require(minimum < -200 && maximum > 200 && std::abs(frequency - expectedTone) < expectedTone * 0.1,
                "PSG output is DC, silent, or has the wrong clock/sample rate");
    }
    if (artifacts) {
        snapshot(output / (std::string(systemId(system)) + ".ppm"), emulator.frame());
        wave(output / (std::string(systemId(system)) + ".wav"), pcm, unsigned(emulator.sampleRate()));
    }
    std::cout << systemId(system) << ": " << emulator.frame().width << 'x' << emulator.frame().height
              << ", " << emulator.coreName() << ", " << pcm.size() / 2 << " stereo frames at " << emulator.sampleRate()
              << " Hz, " << audible << " non-silent samples after bootstrap\n";
}
struct Observation {
    uint64_t video;
    std::array<unsigned char, 8> ram;
    bool operator==(const Observation& other) const { return video == other.video && ram == other.ram; }
};
std::vector<Observation> sequence(Emulator& emulator, SystemType system, std::string& error,
                                 bool fastForward = false) {
    std::vector<Observation> result;
    for (unsigned frame = 0; frame < 17; ++frame) {
        GamepadInput pad{}; pad.connected = true;
        pad.fastForward = fastForward;
        if (frame > 4 && frame < 12) { pad.buttons = 1u << RETRO_DEVICE_ID_JOYPAD_B; pad.start = true; }
        require(emulator.run(pad, error), "State sequence: " + error);
        require(fastForward ? emulator.audio().empty() : !emulator.audio().empty(),
                "Portable fast-forward audio copy policy did not match requested speed");
        result.push_back({pixelHash(emulator.frame()), cartridgeStatus(system)});
    }
    return result;
}
}

int main(int argc, char** argv) {
    try {
        require(argc == 6, "Usage: handheld_tests diagnostic.gb diagnostic.gbc diagnostic.gba diagnostic.z64 output-directory");
        const fs::path output = fs::absolute(argv[5]);
        fs::create_directories(output);
        std::string pattern = (output / "data-XXXXXX").string();
        std::vector<char> directory(pattern.begin(), pattern.end()); directory.push_back(0);
        const char* created = ::mkdtemp(directory.data());
        require(created != nullptr, "Cannot create isolated test data");
        const fs::path data(created);
        fs::create_directories(data / "logs");
        Log log; require(log.open(data.string()), "Cannot open test log");
        Emulator emulator;
        GamepadInput neutral{}; neutral.connected = true;
        std::string error;
        require(!emulator.supportsSaveStates() && !emulator.saveState(error) && !emulator.loadState(error) && !emulator.reset(error),
                "Session operations accepted without a ROM");
        const std::array<SystemType, 3> systems{{SystemType::GameBoy, SystemType::GameBoyColor, SystemType::GameBoyAdvance}};
        std::array<Game, 3> games;
        std::array<fs::path, 3> states;
        std::array<std::vector<unsigned char>, 3> snapshots;
        std::array<std::set<uint32_t>, GameBoyPaletteCount> palettes;
        for (unsigned index = 0; index < systems.size(); ++index) {
            const auto system = systems[index];
            require(readRom(argv[index + 1], games[index], error), error);
            require(games[index].system == system, "Fixture system detection mismatch");
            require(emulator.load(argv[index + 1], data.string(), log, error), "Load: " + error);
            require(emulator.loaded() && emulator.system() == system, "Core manager chose wrong system");
            require(std::string(emulator.coreName()) == (system == SystemType::GameBoyAdvance ? "mGBA" : "SameBoy"), "Core registry chose wrong core");
            verifyBoot(emulator, system, neutral, error, data, true);
            if (system == SystemType::GameBoy) {
                palettes[0] = frameColors(emulator.frame());
                const auto boots = cartridgeStatus(system)[4];
                for (unsigned palette = 1; palette < GameBoyPaletteCount; ++palette) {
                    require(emulator.setGameBoyPalette(palette, error), "Live palette: " + error);
                    runFrames(emulator, neutral, 3, error);
                    palettes[palette] = frameColors(emulator.frame());
                    require(palettes[palette].size() == 4 && palettes[palette] != palettes[0], "GB palette did not change actual pixel colors");
                    for (unsigned previous = 1; previous < palette; ++previous)
                        require(palettes[palette] != palettes[previous], "Two palette selections produced the same colors");
                    require(cartridgeStatus(system)[4] == boots, "Palette change reset the cartridge");
                    snapshot(data / ("gb-palette-" + std::to_string(palette) + ".ppm"), emulator.frame());
                }
                require(!emulator.setGameBoyPalette(GameBoyPaletteCount, error), "Invalid palette accepted");
                require(emulator.setGameBoyPalette(0, error), error);
                runFrames(emulator, neutral, 3, error);
                require(frameColors(emulator.frame()) == palettes[0], "Default grey palette did not restore exactly");
            } else require(!emulator.setGameBoyPalette(0, error), "GB palette applied to another system");
            GamepadInput pressed = neutral;
            pressed.buttons = (1u << RETRO_DEVICE_ID_JOYPAD_B) | (1u << RETRO_DEVICE_ID_JOYPAD_Y) |
                              (1u << RETRO_DEVICE_ID_JOYPAD_UP) | (1u << RETRO_DEVICE_ID_JOYPAD_L) | (1u << RETRO_DEVICE_ID_JOYPAD_R);
            pressed.start = pressed.select = true;
            runFrames(emulator, pressed, 4, error);
            auto status = cartridgeStatus(system);
            require(status[6] == (system == SystemType::GameBoyAdvance ? 0x4f : 0x0f) &&
                    status[7] == (system == SystemType::GameBoyAdvance ? 3 : 4), "Physical A/B/Start/Select/Up/L/R did not reach cartridge input registers");
            pressed.connected = false;
            runFrames(emulator, pressed, 4, error);
            status = cartridgeStatus(system);
            require(status[6] == 0 && status[7] == 0, "Disconnected portable controller retained input");

            auto memory = saveRam(system);
            memory.data[256] = static_cast<unsigned char>(0xa0 + index);
            require(emulator.supportsSaveStates(), "Core does not expose save states after run");
            require(!emulator.loadState(error, SaveStateSlotCount - 1), "Missing state slot was accepted");
            require(emulator.saveState(error), "Save state: " + error);
            states[index] = data / "states" / systemId(system) / (games[index].id + ".slot0.state");
            snapshots[index] = readBytes(states[index]);
            require(snapshots[index].size() > 1000, "Empty state container");
            const auto savedStatus = cartridgeStatus(system);
            const auto first = sequence(emulator, system, error);
            require(first.back().ram[5] != savedStatus[5], "Cartridge CPU counter did not advance");
            require(emulator.loadState(error), "Load state: " + error);
            // The libretro getter must expose the active state-restored memory,
            // including mGBA's temporary savedata mask, not an older backing file.
            require(cartridgeStatus(system) == savedStatus, "State did not restore cartridge RAM exactly");
            require(emulator.frame().pixels.empty() && emulator.audio().empty(), "State load retained stale frontend output");
            const auto second = sequence(emulator, system, error);
            for (size_t step = 0; step < first.size(); ++step)
                require(first[step] == second[step], std::string(systemId(system)) + " state replay step " + std::to_string(step) +
                    ": video " + (first[step].video == second[step].video ? "matches" : "DIFFERS") +
                    ", counter " + std::to_string(first[step].ram[5]) + "/" + std::to_string(second[step].ram[5]) +
                    ", inputs " + std::to_string(first[step].ram[6]) + "/" + std::to_string(second[step].ram[6]));
            require(!emulator.audio().empty(), "State replay lost audio");
            require(emulator.loadState(error), "Restore before fast-forward: " + error);
            const auto accelerated = sequence(emulator, system, error, true);
            require(first == accelerated, "Fast-forward changed cartridge RAM or video at the same emulated frame");
            runFrames(emulator, neutral, 3, error);
            require(!emulator.audio().empty() && emulator.audio().size() < emulator.sampleRate() / 10,
                    "Fast-forward release lost audio or retained a backlog of muted PCM");

            auto damaged = snapshots[index]; damaged.back() ^= 0x40;
            writeBytes(states[index], damaged);
            const auto beforeRejected = cartridgeStatus(system);
            require(!emulator.loadState(error), "Corrupt state payload accepted");
            require(cartridgeStatus(system) == beforeRejected, "Rejected state changed the running cartridge");
            writeBytes(states[index], snapshots[index]);
            if (index) {
                writeBytes(states[index], snapshots[0]);
                require(!emulator.loadState(error), "State from a different system accepted");
                require(cartridgeStatus(system) == beforeRejected, "Wrong-system state changed the running cartridge");
                writeBytes(states[index], snapshots[index]);
            }
            std::array<std::array<unsigned char, 8>, SaveStateSlotCount> slotRam;
            slotRam[0] = savedStatus;
            for (unsigned slot = 1; slot < SaveStateSlotCount; ++slot) {
                runFrames(emulator, neutral, 3, error);
                slotRam[slot] = cartridgeStatus(system);
                require(emulator.saveState(error, slot), "Save numbered slot: " + error);
                const auto slotPath = data / "states" / systemId(system) /
                    (games[index].id + ".slot" + std::to_string(slot) + ".state");
                require(fs::is_regular_file(slotPath), "Numbered state slot missing");
            }
            require(readBytes(states[index]) == snapshots[index], "Writing another slot changed the legacy slot zero");
            require(!emulator.saveState(error, SaveStateSlotCount) && !emulator.loadState(error, SaveStateSlotCount), "Out-of-range state slot accepted");
            for (unsigned slot = SaveStateSlotCount; slot-- > 0;) {
                require(emulator.loadState(error, slot), "Load numbered slot: " + error);
                require(cartridgeStatus(system) == slotRam[slot], "A numbered slot restored another slot's cartridge state");
            }
            const auto boots = cartridgeStatus(system)[4];
            require(emulator.reset(error), "Reset: " + error);
            verifyBoot(emulator, system, neutral, error, data, false);
            require(cartridgeStatus(system)[4] == uint8_t(boots + 1), "Reset did not rerun cartridge initialization");
            require(saveRam(system).data[256] == 0xa0 + index, "Reset lost cartridge save RAM");
            // Loading the next system directly exercises save + teardown + dispatch.
        }
        EmulationConfig n64Config;
        n64Config.audioHle = false; // Upstream N64 states omit the optional hybrid extension state.
        require(emulator.load(argv[4], data.string(), log, error, n64Config), "N64 after handhelds: " + error);
        require(emulator.system() == SystemType::Nintendo64, "N64 core selection failed after GBA");
        runFrames(emulator, neutral, 60, error);
        require(!emulator.frame().pixels.empty() && !emulator.audio().empty(), "N64 lost AV after switching from GBA");
        GamepadInput n64SpeedFlag = neutral; n64SpeedFlag.fastForward = true;
        size_t n64Samples = 0;
        for (unsigned frame = 0; frame < 12; ++frame) {
            require(emulator.run(n64SpeedFlag, error), "N64 with portable speed flag: " + error);
            n64Samples += emulator.audio().size();
        }
        require(n64Samples > 0, "Portable fast-forward flag incorrectly suppressed N64 PCM");
        require(emulator.supportsSaveStates() && emulator.saveState(error), "N64 LLE state creation failed: " + error);
        const auto n64Image = pixelHash(emulator.frame());
        runFrames(emulator, neutral, 3, error);
        require(emulator.loadState(error), "N64 LLE state restore failed: " + error);
        runFrames(emulator, neutral, 3, error);
        require(pixelHash(emulator.frame()) == n64Image, "N64 RGB diagnostic changed after state load");

        for (unsigned index = 0; index < systems.size(); ++index) {
            require(emulator.load(argv[index + 1], data.string(), log, error), "Reload handheld after N64: " + error);
            require(saveRam(systems[index]).data[256] == 0xa0 + index, "Native SRAM did not persist across core switches");
            verifyBoot(emulator, systems[index], neutral, error, data, false);
            // Make the live/native buffer differ from the snapshot, then close
            // immediately after restoring. A stale getter loses the restored save.
            saveRam(systems[index]).data[256] = static_cast<unsigned char>(0x40 + index);
            require(emulator.loadState(error), "State did not survive unload/reload: " + error);
            require(saveRam(systems[index]).data[256] == 0xa0 + index, "State getter exposes old native save instead of restored SRAM");
            require(emulator.reset(error), "Reset immediately after state load failed: " + error);
            require(saveRam(systems[index]).data[256] == 0xa0 + index, "Immediate state-load/reset discarded restored SRAM");
            verifyBoot(emulator, systems[index], neutral, error, data, false);
            saveRam(systems[index]).data[256] = static_cast<unsigned char>(0x50 + index);
            require(emulator.loadState(error), "State load before immediate close failed: " + error);
            const auto restored = cartridgeStatus(systems[index]);
            emulator.unload();
            const auto savePath = data / "saves" / systemId(systems[index]) / (games[index].id + ".srm");
            const auto persisted = readBytes(savePath);
            require(persisted.size() > 256 && persisted[256] == 0xa0 + index &&
                    std::equal(restored.begin(), restored.end(), persisted.begin()), "Immediate state-load/unload persisted stale cartridge SRAM");
            require(emulator.load(argv[index + 1], data.string(), log, error), "Immediate restore/reload: " + error);
            require(saveRam(systems[index]).data[256] == 0xa0 + index, "Immediate restore/unload/reload lost SRAM");
            verifyBoot(emulator, systems[index], neutral, error, data, false);
            require(emulator.loadState(error), "Reloaded cartridge state failed: " + error);
            runFrames(emulator, neutral, 4, error);
            verifyPattern(emulator.frame(), systems[index]);
        }
        emulator.unload();
        require(!emulator.loaded() && emulator.frame().pixels.empty() && emulator.audio().empty(), "Final unload retained outputs");
        for (unsigned index = 0; index < systems.size(); ++index) {
            const auto save = data / "saves" / systemId(systems[index]) / (games[index].id + ".srm");
            const auto bytes = readBytes(save);
            require(bytes.size() == (systems[index] == SystemType::GameBoyAdvance ? 32768 : 8192) && bytes[256] == 0xa0 + index,
                    "Persisted SRAM file has wrong length or contents");
            require(!fs::exists(save.string() + ".tmp"), "Native save left an incomplete atomic write");
        }

        // A different cartridge with the same header must not accept the original state.
        auto variantBytes = readBytes(argv[1]); variantBytes[0x7000] ^= 0xa5;
        const auto variantPath = data / "variant.gb";
        writeBytes(variantPath, variantBytes);
        Game variant; require(readRom(variantPath.string(), variant, error), error);
        require(variant.id != games[0].id, "Different content reused portable identity");
        require(emulator.load(variantPath.string(), data.string(), log, error), error);
        verifyBoot(emulator, SystemType::GameBoy, neutral, error, data, false);
        require(saveRam(SystemType::GameBoy).data[256] != 0xa0, "Different cartridge loaded the original SRAM");
        const auto variantState = data / "states/gb" / (variant.id + ".slot0.state");
        writeBytes(variantState, snapshots[0]);
        const auto before = cartridgeStatus(SystemType::GameBoy);
        require(!emulator.loadState(error) && cartridgeStatus(SystemType::GameBoy) == before, "Cross-ROM state accepted or mutated current session");
        runFrames(emulator, neutral, 2, error);
        emulator.unload();
        EmulationConfig tinted;
        tinted.gbPalette = 3;
        require(emulator.load(argv[1], data.string(), log, error, tinted), "Initial palette configuration: " + error);
        verifyBoot(emulator, SystemType::GameBoy, neutral, error, data, false);
        require(frameColors(emulator.frame()) == palettes[3], "Configured startup palette did not reach SameBoy");
        require(emulator.saveState(error, 4), error);
        require(emulator.setGameBoyPalette(1, error), error);
        runFrames(emulator, neutral, 3, error);
        require(emulator.loadState(error, 4), error);
        runFrames(emulator, neutral, 3, error);
        require(frameColors(emulator.frame()) == palettes[1], "Loading a state reverted the user's current palette");
        require(emulator.reset(error), error);
        verifyBoot(emulator, SystemType::GameBoy, neutral, error, data, false);
        require(frameColors(emulator.frame()) == palettes[1], "Reset lost the user's current palette");
        emulator.unload();
        // Start both A/B runs from a fresh cartridge lifecycle. Core save-state
        // formats do not necessarily restore host-side resampler/filter history,
        // so replaying a state is unsuitable for a bit-exact PCM comparison.
        for (unsigned index = 0; index < systems.size(); ++index) {
            std::vector<Observation> reference;
            std::vector<int16_t> referencePcm;
            for (unsigned pass = 0; pass < 2; ++pass) {
                const auto testData = data / (std::string(systemId(systems[index])) + "-speed-" + std::to_string(pass));
                require(emulator.load(argv[index + 1], testData.string(), log, error), "Fresh speed comparison: " + error);
                std::vector<Observation> observed;
                std::vector<int16_t> releasedPcm;
                for (unsigned frame = 0; frame < 480; ++frame) {
                    GamepadInput pad = neutral;
                    pad.fastForward = pass == 1 && frame >= 360 && frame < 420;
                    if (frame >= 380 && frame < 400) pad.buttons = 1u << RETRO_DEVICE_ID_JOYPAD_B;
                    require(emulator.run(pad, error), "Fresh speed comparison frame: " + error);
                    if (frame >= 360) {
                        observed.push_back({pixelHash(emulator.frame()), cartridgeStatus(systems[index])});
                        if (pad.fastForward) require(emulator.audio().empty(), "Fast-forward retained PCM");
                    }
                    if (frame >= 420) releasedPcm.insert(releasedPcm.end(), emulator.audio().begin(), emulator.audio().end());
                }
                emulator.unload();
                if (!pass) { reference = std::move(observed); referencePcm = std::move(releasedPcm); }
                else {
                    require(observed == reference, "Fresh fast-forward session changed video or cartridge RAM");
                    require(!releasedPcm.empty() && releasedPcm == referencePcm,
                            std::string(systemId(systems[index])) + " speed release changed PCM samples or phase");
                    std::cout << systemId(systems[index]) << ": fast-forward release PCM identical ("
                              << releasedPcm.size() << " samples), 120 video/RAM observations identical\n";
                }
            }
        }
        std::cout << "PASS: original GB/GBC/GBA CPU/video/PSG/input, SRAM persistence, five state slots/replay/rejection, live GB palettes, muted speed/release PCM parity, reset, GB->GBC->GBA->N64->GB switches.\n"
                  << "Artifacts and isolated saves: " << data << '\n';
        return 0;
    } catch (const std::exception& exception) {
        std::cerr << "FAIL: " << exception.what() << '\n';
        return 1;
    }
}
