file(MAKE_DIRECTORY "${DATA_DIR}")
file(REMOVE "${DATA_DIR}/startup.log")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    "SDL_VIDEODRIVER=r2n64_invalid" "R2N64_DATA=${DATA_DIR}"
    "${APP}" --smoke RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 1)
    message(FATAL_ERROR "Expected a handled video failure (exit 1), got ${result}: ${output}${errors}")
endif()
if(NOT EXISTS "${DATA_DIR}/startup.log")
    message(FATAL_ERROR "Startup failure lost its early diagnostic log")
endif()
file(READ "${DATA_DIR}/startup.log" log)
foreach(stage "main: R2RETRO" "SDL_Init begin" "Video initialization: r2n64_invalid not available" "exit: failed")
    string(FIND "${log}" "${stage}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Missing boot failure stage: ${stage}")
    endif()
endforeach()
if(log MATCHES "Platform ready|First frame presented")
    message(FATAL_ERROR "Startup continued after its video initialization failed")
endif()
